version: '3'
services:
  uaa:
    image: scg-demo-uaa:latest
    container_name: uaa
    expose:
      - "8090"
    ports:
      - "8090:8090"
  secured-service:
    image: scg-demo-secured-service:latest
    container_name: resource
    expose:
      - "9000"
  gateway:
    image: scg-demo-security-gateway:latest
    container_name: gateway
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - secured-service
      - uaa