server:
  port: 8883

spring:
  cloud:
    gateway:
      routes:
        - id: toBackendApi1
          uri: http://backend-api-1:8882
          predicates:
            - Path=/api1/**
          filters:
            - RewritePath=/api1/?(?<segment>.*), /$\{segment}
#            - TokenRelay=
            - RemoveRequestHeader=Cookie

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://uaa:8881/uaa/oauth/token
