# the default port is 8080
server:
  port: 8888

# datasource
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:spring_boot_lk;DB_CLOSE_DELAY=-1
    username: sa
    password:
