package cz.kul.snippets.java.java_14_features;

import org.junit.Assert;
import org.junit.Test;

public class Java14Features {

  @Test
  public void records() {
    /*

    * Records are immutable data classes that require only the type and name of fields.
    * The equals, hashCode, and toString methods, as well as the private, final fields and public constructor,
      are generated by the Java compiler.

     */

    // automatically generated constructor
    Person monica = new Person("Monica", "New York");

    // automatically generated getter (it is NOT java beans getter, it does not start with "get")
    Assert.assertEquals("Monica", monica.name());

    // automatically generated equals method
    Assert.assertEquals(new Person("Monica", "New York"), monica);

    // Automatically generated toString
    Assert.assertEquals("Person[name=Monica, address=New York]", monica.toString());

  }

  record Person (String name, String address) {}

}
