server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: api1
          uri: http://localhost:8081
          predicates:
            - Path=/api1/**
          filters:
            - RewritePath=/api1/?(?<segment>.*), /$\{segment}
        - id: api2
          uri: http://localhost:8082
          predicates:
            - Path=/api2/**
          filters:
            - RewritePath=/api2/?(?<segment>.*), /$\{segment}
#        - id: openapi
#          uri: http://localhost:${server.port}
#          predicates:
#            - Path=/v3/api-docs/**
#          filters:
#            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

#springdoc:
#  swagger-ui:
#    urls[0]:
#      url: http://localhost:8080/v3/api-docs/api1
#      name: api1
#    urls[1]:
#      url: http://localhost:8080/v3/api-docs/api2
#      name: api2
