//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.01 at 09:50:24 PM CET 
//


package cz.kul.weather.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for WeatherServiceWeather complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WeatherServiceWeather">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tempC" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="relativeHumididy" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="windDegrees" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="windSpeed" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="feelslikeTempC" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="locationLongitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="locationLangitude" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="observationTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WeatherServiceWeather", propOrder = {
    "tempC",
    "relativeHumididy",
    "windDegrees",
    "windSpeed",
    "feelslikeTempC",
    "location",
    "locationLongitude",
    "locationLangitude",
    "observationTime"
})
public class WeatherServiceWeather {

    @XmlElement(required = true, type = Float.class, nillable = true)
    protected Float tempC;
    @XmlElement(required = true, type = Float.class, nillable = true)
    protected Float relativeHumididy;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer windDegrees;
    @XmlElement(required = true, type = Float.class, nillable = true)
    protected Float windSpeed;
    @XmlElement(required = true, type = Float.class, nillable = true)
    protected Float feelslikeTempC;
    @XmlElement(required = true, nillable = true)
    protected String location;
    @XmlElement(required = true, type = Float.class, nillable = true)
    protected Float locationLongitude;
    @XmlElement(required = true, type = Float.class, nillable = true)
    protected Float locationLangitude;
    @XmlElement(required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar observationTime;

    /**
     * Gets the value of the tempC property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getTempC() {
        return tempC;
    }

    /**
     * Sets the value of the tempC property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setTempC(Float value) {
        this.tempC = value;
    }

    /**
     * Gets the value of the relativeHumididy property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getRelativeHumididy() {
        return relativeHumididy;
    }

    /**
     * Sets the value of the relativeHumididy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setRelativeHumididy(Float value) {
        this.relativeHumididy = value;
    }

    /**
     * Gets the value of the windDegrees property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWindDegrees() {
        return windDegrees;
    }

    /**
     * Sets the value of the windDegrees property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWindDegrees(Integer value) {
        this.windDegrees = value;
    }

    /**
     * Gets the value of the windSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getWindSpeed() {
        return windSpeed;
    }

    /**
     * Sets the value of the windSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setWindSpeed(Float value) {
        this.windSpeed = value;
    }

    /**
     * Gets the value of the feelslikeTempC property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getFeelslikeTempC() {
        return feelslikeTempC;
    }

    /**
     * Sets the value of the feelslikeTempC property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setFeelslikeTempC(Float value) {
        this.feelslikeTempC = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the locationLongitude property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getLocationLongitude() {
        return locationLongitude;
    }

    /**
     * Sets the value of the locationLongitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setLocationLongitude(Float value) {
        this.locationLongitude = value;
    }

    /**
     * Gets the value of the locationLangitude property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getLocationLangitude() {
        return locationLangitude;
    }

    /**
     * Sets the value of the locationLangitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setLocationLangitude(Float value) {
        this.locationLangitude = value;
    }

    /**
     * Gets the value of the observationTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getObservationTime() {
        return observationTime;
    }

    /**
     * Sets the value of the observationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setObservationTime(XMLGregorianCalendar value) {
        this.observationTime = value;
    }

}
