version: '3'
services:

  uaa:
    image: example-scg-with-oauth2-uaa:latest
    expose:
      - "8881"
    ports:
      - "8881:8881"

  backend-api-1:
    image: example-scg-with-oauth2-backend-api-1:latest
    expose:
      - "8882"
    ports:
      - "8882:8882"

  gateway:
    image: example-scg-with-oauth2-gateway:latest
    expose:
      - "8883"
    ports:
      - "8883:8883"

  client:
    image: example-scg-with-oauth2-client:latest
    expose:
      - "8884"
    ports:
      - "8884:8884"
